config/routes.rb
Brograms::Application.routes.draw do

  resources :brograms, :only => [:new, :create]

  root :to => 'brograms#new'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/brograms_controller.rb
class BrogramsController < ApplicationController
  
  def new
    
  end
  
  def create
    BrogramMailer.brogram(params[:brogram]).deliver
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brograms/create.html.erb
 <div class="row">
	<div class="twelve columns">
	  
	  <% if params[:brogram][:zipcode] == '95008' %>
		  <!-- Confirmed Code -->
  		<h2 class="space">Confirmed!</h2>
  		<h4>Thanks for your brogram!</h4>
  		<h5>We will attempt to deliver this since you are in the Campbell area.</h5>
      <!-- <p>Share Your Brogram:
        <a href="https://twitter.com/share" class="twitter-share-button">Twitter</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script> 
        <a href="facebook.com/sharer.php">Facebook</a>
      </p> -->
    <% else %>
	
		  <!-- Outside Campbell Code -->
  		<h2 class="space">Oh Noes!</h2>
  		<h4>We're sorry!</h4>
  		<h5>This is a pilot in the Campbell, CA area we will try to add your area someday...</h5>
      <!-- <p>Share Your Brogram:
        <a href="https://twitter.com/share" class="twitter-share-button">Twitter</a>
          <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script> 
        <a href="facebook.com/sharer.php">Facebook</a>
      </p> -->
    <% end %>
	   <hr />
	</div>
</div>
<div class="row">
	<div class="six columns">
		<h3>Sender:</h3>
		<p class="big">Name: <%= params[:brogram][:yourname] %></p>
		<p class="big">Email: <%= params[:brogram][:youremail] %></p>
	</div>
	<div class="six columns">
		<h3>Recipient:</h3>
		<p class="big">Name: <%= params[:brogram][:broname] %></p>
		<p class="big">Address: <%= params[:brogram][:address] %><p>
		<p class="big"><%= params[:brogram][:city] %>, <%= params[:brogram][:zipcode] %></p>
		<p class="big">Type: <%= params[:brogram][:type] %></p>
		<p>
			<!-- Image of Type Selected -->
      <!-- <img src="http://placehold.it/200x200"></img> -->
		</p>
	</div>
</div>

app/views/brograms/new.html.erb
<div class="row">
	<div class="twelve columns">
		<div class="well">
			<p class="putcenter">Inspired by Bro Code, Brogram is a special message<br/>
				from one bro to another, delivered by a bro.
			</p>
		</div>
	</div>
</div>

<!-- Video -->
<div class="row">
	<div class="wrapper">	
		<div class="flex-video">
		  <iframe src="http://fast.wistia.com/embed/iframe/ec0c351a73?controlsVisibleOnLoad=false" allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed"></iframe>
		</div>
	</div>
</div>
<br />
	
<!-- Images -->	
<div class="row">
	<div class="twelve columns">
		<p class="options">Three browesome options to choose from:</p>
	</div>
</div>
<div class="row">
	<div class="four columns">
		<p><%= image_tag 'brograms/hifive.png' %></p>	
	</div>
	<div class="four columns">
		<p><%= image_tag 'brograms/icebox.png' %></p>	
	</div>
	<div class="four columns">
		<p><%= image_tag 'brograms/lovebox.png' %></p>
	</div>
</div>

<!-- Web Form -->

<div class="row">
	<div class="twelve columns">
	  <%= form_tag brograms_path, :class => 'nice custom well bottom' %>
		<form class="nice custom well bottom" action="confirmation.html" id="sendBrogram">
	  		<h3 class="send">Send a Brogram!</h3>
			<div class="row">
		   		<div class="six columns">
					<p>  
						<label for="yourname"></label>  
						<input class="input-text expand" type="text" name="brogram[yourname]" id="yourname" placeholder="Your Name"/> 
		    		</p> 
    		</div> 
    	   		<div class="six columns">
		    		<p class="input-text">  
		    			<label for="youremail"></label>  
						<input class="input-text expand" type="text" name="brogram[youremail]" id="youremail" placeholder="Your Email" /> 
		    		</p> 
    	   		</div>
    	  	</div>
    	  	<div class="row">
	    		<p class="choice">Send my bro this brogram:</p> 
	    		<ul class="type-of-brogram">
	    			<li class="mini-hf"><label for="five"><input type="radio" name="brogram[type]" value="High Five" CHECKED id="five" style="display: none;" /><span class="custom radio selected"></span></label></li>
	    			<li class="mini-ic"><label for="ice"><input type="radio" name="brogram[type]" value="Ice" id="five" style="display: none;" /><span class="custom radio"></span></label></li>
	    			<li class="mini-lb"><label for="romance"><input type="radio" name="brogram[type]" value="Love Box" id="five" style="display: none;" /><span class="custom radio"></span></label></li>
	    		</ul>
    		</div>
    		<div class="row">
		   		<div class="six columns">
		    		<p>  
		    			<label for="broname"></label>  
						<input class="input-text expand" type="text" name="brogram[broname]" id="broname" placeholder="Bro's Name" /> 
		    		</p> 
		    	</div>
		    	<div class="six columns">
		    		<p>  
		    			<label for="broname"></label>  
						<input class="input-text expand" type="text" name="brogram[broemail]" id="broemail" placeholder="Bro's Email" /> 
		    		</p>
		    	</div>
		    </div>
		    <div class="row">
		    	<div class="six columns">
		    		<p>  
						<label for="address"></label> 
						<input class="input-text expand" type="text" name="brogram[address]" id="address" placeholder="Bro's Address" /> 
		    		</p>
		    	</div>
		    	<div class="four columns">
						<label for="city"></label> 
						<input type="text" class="expand small input-text" name="brogram[city]" id="city" placeholder="City" /> 
		    		
		    	</div>
		    	<div class="two columns"> 
						<label for="zipcode"></label> 
						<input type="text" class="expand small input-text" name="brogram[zipcode]" id="zipcode" placeholder="Zip Code" />  
		    	</div>
    		</div>
        <!-- <p> 
            <label for="time">Time</label>  
            <select id="brogramTime">
            <option>This is a dropdown</option>
            <option>This is another option</option>
            <option>Look, a third option</option>
          </select>
          </p> -->
    		<p class="submit">  
    			<input type="submit" id="submitBrogram" /> 
        		<!--<input class="large nice radius button" type="submit" value="Submit" /> --> 
    		</p> 
    		
    		<hr />
		</form>	
	</div>	
</div>

app/views/layouts/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-2195009-36']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- april fools -->
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en"> <!--<![endif]-->
<head>
	<meta charset="utf-8" />

	<!-- Set the viewport width to device width for mobile -->
	<meta name="viewport" content="width=device-width" />

	<title>Brograms - Hand-Delivered Messages From Bro To Bro</title>
	
	<meta name="keywords" content="bros, delivery, messages, deeds, bro code, high five, ice, bros icing bros, you got iced, love box, brotection, april fool's, jokes, gags" />
	<meta name="description" content="Brograms are special hand-delivered messages sent from one bro to another. Send one today." />
  
	<!-- Included CSS Files -->
	<%= stylesheet_link_tag "foundation", "brograms", :media => "all" %>
	<%= csrf_meta_tags %>

	<!--[if lt IE 9]>
		<link rel="stylesheet" href="stylesheets/ie.css">
	<![endif]-->


	<!-- IE Fix for HTML5 Tags -->
	<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->

  <%= render :partial => 'layouts/google_analytics' if Rails.env.production? %>
</head>
<body>

	<!-- container -->
	<div class="container">
	  
	  <!-- Header -->
    <header class="row">
    	<div class="twelve columns">
    	  <%= image_tag 'brograms/header1.png', :class => 'heading' %>
    	</div>
    </header>

    <%= yield %>
	     
	  <!-- Footer -->	
    <div class="row">
      <div class="twelve columns">
				<p class="red">MADE BY <a href="http://www.zurb.com"> <%= image_tag 'brograms/logo.png' %></a></p>
			</div>
    </div>
  </div>
  <!-- container -->



	<!-- Included JS Files -->
	<%= javascript_include_tag "jquery", "foundation" %>

</body>
</html>